### ISSUE TITLE
Doesn't appear to work

### ISSUE THREAD

**Issue by patientplatypus** [wojtekmaj/react-clock#7]
In my nextjs project I imported and ran following the directions (simple example using pre-built css). I got the below error code. I'd love to use your clock but it doesn't look like it works :/.

```
Unexpected token .

/Users/patientplatypus/Documents/patientplatypus.com/forum/node_modules/react-clock/dist/Clock.css:1
(function (exports, require, module, __filename, __dirname) { .react-clock {
                                                              ^

SyntaxError: Unexpected token .
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/patientplatypus/Documents/patientplatypus.com/forum/node_modules/react-clock/dist/entry.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

**Comment by wojtekmaj** [comment]
React-Clock is automatically imported with styles (`.css`), so you need an appropriate loader for it to work. On non-web environments please refer to these instructions to [import React-Clock without styles](https://github.com/wojtekmaj/react-clock#custom-styling).
